USE [Teste_WebAPI]
GO


--### OPERADORAS ###
INSERT [dbo].[OPERADORA] ([NOME], [CODIGO], [CATEGORIA], [PRECO]) VALUES ('Oi', 31, 'Celular', 2)
GO
INSERT [dbo].[OPERADORA] ([NOME], [CODIGO], [CATEGORIA], [PRECO]) VALUES ('Vivo', 15, 'Celular', 1)
GO
INSERT [dbo].[OPERADORA] ([NOME], [CODIGO], [CATEGORIA], [PRECO]) VALUES ('Tim', 41, 'Celular', 3)
GO
INSERT [dbo].[OPERADORA] ([NOME], [CODIGO], [CATEGORIA], [PRECO]) VALUES ('GVT', 25, 'Fixo', 1)
GO
INSERT [dbo].[OPERADORA] ([NOME], [CODIGO], [CATEGORIA], [PRECO]) VALUES ('Embratel', 21, N'Fixo', 2)
GO



--### CONTATOS ###
INSERT [dbo].[CONTATO] ([NOME], [TELEFONE], [DATA], [OPERADORA_ID], [SERIAL]) VALUES ('Lucas', '98782-5257', GETDATE(), 1, '@2U\B')
GO
INSERT [dbo].[CONTATO] ([NOME], [TELEFONE], [DATA], [OPERADORA_ID], [SERIAL]) VALUES ('Anna', '98756-8309', GETDATE(), 1, '&?I5.')
GO
INSERT [dbo].[CONTATO] ([NOME], [TELEFONE], [DATA], [OPERADORA_ID], [SERIAL]) VALUES ('Bento Magno', '8888-9999', GETDATE(), 5, 'RQ<[8')
GO