CREATE TABLE [dbo].[CONTATO]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [NOME] VARCHAR(100) NOT NULL, 
    [TELEFONE] VARCHAR(20) NOT NULL, 
    [DATA] DATETIME NULL, 
    [OPERADORA_ID] INT NULL, 
    [SERIAL] VARCHAR(20) NULL, 
    CONSTRAINT [FK_CONTATO__OPERADORA] FOREIGN KEY (OPERADORA_ID) REFERENCES [OPERADORA]([ID])
)
